services:
  # 1. Backend Service (Docker)
  - type: web
    name: hospital-backend
    env: docker
    dockerContext: ./backend
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false

  # 2. Frontend Service (Node.js Web Service)
  - type: web
    name: hospital-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist -l $PORT
    plan: free
    region: singapore
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hospital-backend
          property: url
